import crypto from 'crypto';
import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import { Parcel, UserRole } from '../../shared/types';
import { config } from '../config';
import { repository } from '../repo';
import { serializeParcel } from './serializers';
import { evaluateParcelRisks } from './riskEngine';
import { appendLedgerEntry } from './ledgerService';

export interface GeneratedDossier {
  pdfBuffer: Buffer;
  pdfHash: string;
  documentId: string;
  generatedAt: string;
  role: UserRole;
}

/**
 * Generates an official, role-aware Cadastral Dossier PDF with PDFKit
 */
export async function generateDossierPdf(params: {
  parcel: Parcel;
  actor: {
    id: string;
    role: UserRole;
    fullName: string;
  };
}): Promise<GeneratedDossier> {
  const { parcel, actor } = params;
  const role = actor.role;

  // 1. Apply physical role serialization so citizen dossiers contain NO forbidden keys
  const serialized = serializeParcel(parcel, role);

  // 2. Fetch context for risk rules
  const allParcels = (await repository.getParcels({ limit: 100 })).items;
  const waterbodies = await repository.getWaterbodies();
  const risks = evaluateParcelRisks(parcel, allParcels, waterbodies, role);

  const documentId = `KSH-DOS-2026-${parcel.ulpin.slice(0, 6)}-${Date.now().toString().slice(-6)}`;
  const generatedAt = new Date().toISOString();

  // 3. Generate QR Code linking to verification
  const baseUrl = config.publicBaseUrl.replace(/\/$/, '');
  const qrTargetUrl = `${baseUrl}/verify?docId=${documentId}&ulpin=${parcel.ulpin}`;
  const qrBuffer = await QRCode.toBuffer(qrTargetUrl, {
    width: 110,
    margin: 1,
    color: {
      dark: '#0B3D6E',
      light: '#FFFFFF'
    }
  });

  // 4. Construct PDF Document
  const doc = new PDFDocument({
    margin: 40,
    size: 'A4',
    info: {
      Title: `Cadastral Dossier - ${parcel.displayUlpin}`,
      Author: 'KSHETRA OS Land Governance DPI',
      Subject: 'Smart India Hackathon 2026 Prototype',
      Keywords: 'cadastre, ULPIN, land records, SIH26014'
    }
  });

  const chunks: Buffer[] = [];
  doc.on('data', chunk => chunks.push(chunk));

  const pdfPromise = new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  // --- PDF Header & Banner ---
  doc.rect(40, 40, 515, 3).fill('#0B3D6E');

  doc.moveDown(0.8);
  doc.fontSize(16).fillColor('#0B3D6E').text('KSHETRA OS — UNIFIED CADASTRAL OPERATING SYSTEM', { align: 'center' });
  doc.fontSize(8).fillColor('#64748B').text('Smart India Hackathon 2026 Prototype · Not an official Government of India website · PS SIH26014', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(9).fillColor('#334155').text(`OFFICIAL CADASTRAL DOSSIER & RECORD OF RIGHTS`, { align: 'center', underline: true });
  doc.moveDown(1);

  // Metadata Row
  const startY = doc.y;
  doc.fontSize(9).fillColor('#0F172A');
  doc.text(`Document ID: `, 40, startY, { continued: true }).font('Helvetica-Bold').text(documentId);
  doc.font('Helvetica').text(`Issuance Date: `, 40, doc.y, { continued: true }).font('Helvetica-Bold').text(generatedAt);
  doc.font('Helvetica').text(`Generated By: `, 40, doc.y, { continued: true }).font('Helvetica-Bold').text(`${actor.fullName} (${role.toUpperCase()})`);

  // QR Code on right
  doc.image(qrBuffer, 440, startY - 10, { width: 90 });
  doc.fontSize(7).fillColor('#64748B').text('Scan to Verify Hash', 445, startY + 82, { width: 85, align: 'center' });

  doc.y = startY + 95;

  // --- Section 1: Spatial & Geodetic Cadastre ---
  doc.rect(40, doc.y, 515, 18).fill('#F1F5F9');
  doc.fontSize(9).fillColor('#0B3D6E').font('Helvetica-Bold').text(' 1. SPATIAL & GEODETIC PARCEL IDENTIFICATION', 45, doc.y + 4);
  doc.moveDown(0.8);

  doc.font('Helvetica').fontSize(9).fillColor('#1E293B');
  doc.text(`Bhu-Aadhaar ULPIN: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(parcel.displayUlpin);
  doc.font('Helvetica').text(`Survey Number: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(parcel.surveyNumber);
  doc.font('Helvetica').text(`Administrative District: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(`${parcel.district}, ${parcel.state} (PIN: ${parcel.pinCode})`);
  doc.font('Helvetica').text(`Cadastral Area: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(`${parcel.areaSqm} sq.m (${parcel.areaAcres} acres)`);
  doc.font('Helvetica').text(`Centroid Coordinates: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(`${parcel.centroidLat.toFixed(6)}° N, ${parcel.centroidLon.toFixed(6)}° E`);
  doc.moveDown(1);

  // --- Section 2: Ownership & Encumbrance (Role-Masked) ---
  doc.rect(40, doc.y, 515, 18).fill('#F1F5F9');
  doc.fontSize(9).fillColor('#0B3D6E').font('Helvetica-Bold').text(' 2. REVENUE REGISTRY & LEGAL TITLE DEEDS', 45, doc.y + 4);
  doc.moveDown(0.8);

  const ownership = serialized.ownership || parcel.ownership;
  const encumbrance = serialized.encumbrance || parcel.encumbrance;

  doc.font('Helvetica').fontSize(9).fillColor('#1E293B');
  doc.text(`Primary Title Holder: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(ownership?.ownerName || 'N/A');
  doc.font('Helvetica').text(`Registration Date: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(ownership?.registrationDate || 'N/A');
  doc.font('Helvetica').text(`Registration Reg No: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(`${ownership?.registrationNumber || 'N/A'} (SRO: ${ownership?.subRegistrarOffice || 'N/A'})`);

  if (role !== 'citizen' && ownership?.coOwners) {
    doc.font('Helvetica').text(`Co-Owners: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(ownership.coOwners.join(', '));
  } else if (role === 'citizen') {
    doc.font('Helvetica-Oblique').fontSize(8).fillColor('#64748B').text('* Co-owner personal identities protected under citizen data masking (Layer 2).', 45, doc.y);
    doc.font('Helvetica').fontSize(9).fillColor('#1E293B');
  }

  // Encumbrance
  doc.moveDown(0.5);
  doc.text(`Encumbrance Status: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(
    encumbrance?.disputeFlag ? 'ACTIVE JUDICIAL LITIGATION' : encumbrance?.hasMortgage ? 'MORTGAGED' : 'CLEAR TITLE / NIL ENCUMBRANCE'
  );

  if (role !== 'citizen' && encumbrance) {
    if (encumbrance.courtCaseNumber) {
      doc.font('Helvetica').text(`Civil Case Docket: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(`${encumbrance.courtCaseNumber} (Stay: ${encumbrance.stayOrderDetails || 'Active'})`);
    }
    if (encumbrance.mortgageDetails) {
      doc.font('Helvetica').text(`Registered Mortgage Lien: `, 45, doc.y, { continued: true }).font('Helvetica-Bold').text(
        `${encumbrance.mortgageDetails.lenderName} — ₹${encumbrance.mortgageDetails.loanAmountInr.toLocaleString('en-IN')}`
      );
    }
  }
  doc.moveDown(1);

  // --- Section 3: Automated Risk Rules & Statutory Findings ---
  doc.rect(40, doc.y, 515, 18).fill('#F1F5F9');
  doc.fontSize(9).fillColor('#0B3D6E').font('Helvetica-Bold').text(` 3. AUTOMATED RISK ENGINE VERIFICATION (${risks.length} FINDINGS)`, 45, doc.y + 4);
  doc.moveDown(0.8);

  if (risks.length === 0) {
    doc.fontSize(9).fillColor('#059669').font('Helvetica-Bold').text('✓ Zero risk flags detected. Title complies with all spatial, zoning, and encumbrance checks.', 45, doc.y);
  } else {
    for (const r of risks) {
      const color = r.severity === 'rose' ? '#BE123C' : r.severity === 'amber' ? '#D97706' : '#0284C7';
      doc.fontSize(8.5).fillColor(color).font('Helvetica-Bold').text(`[${r.ruleId} - ${r.severity.toUpperCase()}] ${r.plainReason}`, 45, doc.y);
      doc.fontSize(7.5).fillColor('#64748B').font('Helvetica').text(`Responsible Office: ${r.responsibleOffice}`, 55, doc.y);
      doc.moveDown(0.4);
    }
  }

  doc.moveDown(1);

  // --- Section 4: Cryptographic Anchor & Ledger Seal ---
  doc.rect(40, doc.y, 515, 18).fill('#F1F5F9');
  doc.fontSize(9).fillColor('#0B3D6E').font('Helvetica-Bold').text(' 4. CRYPTOGRAPHIC INTEGRITY & LEDGER ANCHOR', 45, doc.y + 4);
  doc.moveDown(0.8);

  doc.fontSize(8).fillColor('#334155').font('Helvetica');
  doc.text('This document is electronically sealed and cryptographically anchored into the KSHETRA OS SHA-256 audit ledger.', 45, doc.y);
  doc.text(`Digital PUBLIC Public Key: KSH-DPI-ED25519-SIG-2026`, 45, doc.y);
  doc.text(`Verification Endpoint: POST /api/dossier/verify (multipart PDF upload)`, 45, doc.y);

  doc.end();

  const pdfBuffer = await pdfPromise;
  const pdfHash = crypto.createHash('sha256').update(pdfBuffer).digest('hex');

  // 5. Append DOSSIER_ISSUED block into the persistent ledger
  await appendLedgerEntry({
    action: 'DOSSIER_ISSUED',
    actorRole: actor.role,
    actorName: actor.fullName,
    actorId: actor.id,
    ulpin: parcel.ulpin,
    detail: `Official Cadastral Dossier issued for ${parcel.displayUlpin} under ${role.toUpperCase()} role. PDF SHA-256: ${pdfHash.slice(0, 16)}...`,
    payloadHash: pdfHash,
    payload: {
      documentId,
      pdfHash,
      ulpin: parcel.ulpin,
      role,
      sizeBytes: pdfBuffer.length
    }
  });

  return {
    pdfBuffer,
    pdfHash,
    documentId,
    generatedAt,
    role
  };
}

/**
 * Accepts an uploaded PDF buffer, recalculates its SHA-256 hash,
 * and searches the cryptographic ledger for a MATCH or NO MATCH.
 */
export async function verifyDossierPdf(buffer: Buffer): Promise<{
  matched: boolean;
  status: 'MATCH' | 'NO_MATCH';
  calculatedHash: string;
  block?: {
    blockIndex: number;
    timestamp: string;
    action: string;
    details: string;
    currentHash: string;
  };
  verifiedAt: string;
}> {
  const calculatedHash = crypto.createHash('sha256').update(buffer).digest('hex');
  const blocks = await repository.getLedgerBlocks();
  const verifiedAt = new Date().toISOString();

  // Search for matching dossier issue record in ledger
  const match = blocks.find(b => {
    if (b.action !== 'DOSSIER_ISSUED') return false;
    const meta = b.metadataPayload as any;
    if (meta?.payloadHash === calculatedHash) return true;
    if (meta?.data?.pdfHash === calculatedHash) return true;
    return false;
  });

  if (match) {
    return {
      matched: true,
      status: 'MATCH',
      calculatedHash,
      block: {
        blockIndex: match.blockIndex,
        timestamp: match.timestamp,
        action: match.action,
        details: match.details,
        currentHash: match.currentHash
      },
      verifiedAt
    };
  }

  return {
    matched: false,
    status: 'NO_MATCH',
    calculatedHash,
    verifiedAt
  };
}
